--- 

- hosts: webserver
  become: true
  gather_facts: false
  vars:
    http_port: 3000
    site_folder: "awesome-site"
    site_repo: "https://github.com/mrocklin/streamz.git"
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
    - name: start nginx
      service:
        name: nginx
        state: started
    - name: add the project folder
      git:
        repo: "{{ site_repo }}" 
        dest: "/var/www/{{ site_folder }}"
    - name: add the nginx configuration
      template:
        src: "{{ site_folder }}.nginx.conf.j2"
        dest: "/etc/nginx/sites-available/{{ site_folder }}"
    - name: deactivate the default nginx configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: activate the configuration
      file:
        src: "/etc/nginx/sites-available/{{ site_folder }}"
        dest: "/etc/nginx/sites-enabled/{{ site_folder }}"
        state: link
    - name: restart nginx
      service:
        name: nginx
        state: restarted
   
        

